# Without this, tmux will eat the colours!
export TERM=screen-256color

# Prevent zsh from renaming my terminals
export DISABLE_AUTO_TITLE=true

export GOPATH=$HOME/go
export PATH=$HOME/.cargo/bin:$HOME/.local/bin:$GOPATH/bin:$HOME/bin:/usr/local/go/bin:$PATH
export HOSTNAME=$(hostname)

source ~/.zsh/antigen/antigen.zsh
source ~/.zsh/.antigenrc

# Keep 10000 lines of history within the shell and save it to ~/.zsh_history:
HISTSIZE=10000
SAVEHIST=10000
HISTFILE=~/.zsh_history

# Use Vi key bindings
bindkey -v

# Reduce the timeout on escape sequences on zsh:
# wait 10ms. (send to vim/tmux faster)
export KEYTIMEOUT=1

# Set host if not set. Bash would normally set this.
[ -z $HOST ] && export HOST=`hostname`

# Source all custom configs
for file in $(find ~/config/zsh/.zsh.d/ -type f | sort)
do
    source $file
done

eval $(thefuck --alias)

export WORKON_HOME=$HOME/.virtualenvs
export PIP_VIRTUALENV_BASE=WORKON_HOME
export PIP_REQUIRE_VIRTUALENV=true

function which_skip_alias {
    # Ignore alias -- trying to find the binary
    which -a "$@" | grep -v alias | head -n1
}
export SYSTEM_PIP=`which_skip_alias pip`
function syspip {
    PIP_USER='yes' PIP_REQUIRE_VIRTUALENV="" $SYSTEM_PIP "$@"
}
export SYSTEM_PIP3=`which_skip_alias pip3`
function syspip3 {
    PIP_USER='yes' PIP_REQUIRE_VIRTUALENV="" $SYSTEM_PIP3 "$@"
}
export EDITOR="nvim"

# Don't let me freeze the terminal with ctrl-s.
# It's annoying and I'm fairly certain never useful these days.
stty -ixon

# Vim Pager
if hash vimpager 2>/dev/null; then
    export PAGER=/usr/local/bin/vimpager
    alias less=$PAGER
    alias zless=$PAGER
fi

NPM_PACKAGES="${HOME}/.npm-packages"
export PATH="$NPM_PACKAGES/bin:$PATH"

# Unset manpath so we can inherit from /etc/manpath via the `manpath` command
unset MANPATH # delete if you already modified MANPATH elsewhere in your config
export MANPATH="$NPM_PACKAGES/share/man:$(manpath)"

# Insert all matches with C-x C-x
zle -C all-matches complete-word _my_generic
zstyle ':completion:all-matches::::' completer _all_matches
zstyle ':completion:all-matches:*' old-matches only
_my_generic () {
      local ZSH_TRACE_GENERIC_WIDGET=  # works with "setopt nounset"
        _generic "$@"
    }
bindkey '^X^X' all-matches

# tabtab source for electron-forge package
# uninstall by removing these lines or running `tabtab uninstall electron-forge`
[[ -f /home/darndt/git/ganache/node_modules/tabtab/.completions/electron-forge.zsh ]] && . /home/darndt/git/ganache/node_modules/tabtab/.completions/electron-forge.zsh

# Auto start ssh-agent
eval `keychain --eval 2>/dev/null`

if [[ -e $HOME/.secrets ]]; then
    source $HOME/.secrets
fi

if [[ -e $HOME/.local_zsh_rc ]]; then
    source $HOME/.local_zsh_rc
fi
