---

# YouCompleteMe
- block:
  - name: Install YouCompleteMe dependencies
    apt: name={{ item }} state=present
    become: true
    with_items:
      - "{{ ycm_packages }}"

  - name: Install YouCompleteMe python modules
    pip:
      name: neovim
      executable: pip3
      extra_args: --user
    environment:
      PIP_REQUIRE_VIRTUALENV: ""

  - name: Check if ycmd exists
    stat:
      path: /usr/bin/ycmd
    register: ycmd_stat

  - name: Run YouCompleteMe install (this may take a while)
    when: ycmd_stat.stat.exists == False
    shell: "python {{ vim_runtime_dir }}/sources_non_forked/YouCompleteMe/install.py --clang-completer"


  tags:
    - ycm

# Ctags
- block:
  - name: Add universal-ctags ppa
    apt_repository:
      repo: "{{ universal_ctags_ppa }}"
      state: present
    when: ansible_os_family == "Debian"
    become: true

  - name: Install ctags
    apt: name="universal-ctags" state=present
    become: true

  - name: ensure ctags directory exists
    file:
      path: "{{ ansible_env.HOME }}/.ctags.d"
      state: directory

  - name: Copy ctags rules
    copy:
      src: ctags
      dest: "{{ ansible_env.HOME }}/.ctags.d/default.ctags"

  tags: ctags
