- name: Install thefuck
  pip:
    name: thefuck
    executable: pip3
    extra_args: --user
  environment:
    PIP_REQUIRE_VIRTUALENV: ""

- name: Install virtualenvwrapper
  pip:
    name: virtualenvwrapper
    executable: pip3
    extra_args: --user
  environment:
    PIP_REQUIRE_VIRTUALENV: ""

- name: Install htop
  package:
    name: htop
    state: present
  become: true

- name: Install silversearcher-ag
  package:
    name: silversearcher-ag
    state: present
  become: true

- name: Install keychain
  package:
    name: keychain
    state: present
  become: true
