# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.provider "virtualbox" do |vb|
      vb.memory = 1024
  end
  config.vm.define :master do |master_config|
    master_config.vm.box = "ubuntu/xenial64"
    master_config.vm.host_name = 'configtest.local'
    master_config.vm.synced_folder "../../", "/home/vagrant/config"
  end

  config.vm.provision "shell", inline: "DEBIAN_FRONTEND=noninteractive apt-get update"
  config.vm.provision "shell", inline: "DEBIAN_FRONTEND=noninteractive apt-get -y install git swapspace python"
  config.vm.provision "shell", inline: "DEBIAN_FRONTEND=noninteractive locale-gen en_CA.UTF-8"
end
