---
- hosts: all
  vars:
    git_templates_directory: "~{{ ansible_user_id }}/.git_template"
  tasks:
  - name: ensure github template hooks directory exists
    file: 
      path: "{{ git_templates_directory }}/hooks" 
      state: directory
  - name: copy git hooks templates
    template: 
      src: "git_template/hooks/{{ item.filename }}"
      dest: "{{ git_templates_directory }}/hooks/{{ item.filename }}"
    with_items:
      - { filename: "ctags" }
      - { filename: "post-checkout" }
      - { filename: "post-commit" }
      - { filename: "post-merge" }
      - { filename: "post-rewrite" }
      - { filename: "pre-push" }
